const translations = {
    ko: {
        nav_home: "홈", nav_blog: "블로그", nav_about: "소개", nav_test: "AI 제자상", nav_checkup: "신앙 점검", nav_dashboard: "대시보드", nav_privacy: "개인정보처리방침", nav_terms: "이용약관", site_logo: "영국 데일리 바이블",
        main_title: "오늘의 성경 구절", loading: "말씀을 불러오고 있습니다...", btn_new_verse: "새로운 구절", btn_share: "말씀 공유", pilgrim_title: "오늘의 순례자 여정", pilgrim_desc: "인생이라는 순례길을 걷는 당신을 위한 오늘의 영적 발걸음입니다.", btn_start_test: "테스트 시작하기", checkup_promo_desc: "인공지능이 분석하는 나의 영적 특성, 13가지 성경적 유형으로 확인해보세요.", heritage_title: "신앙과 예술의 만남", heritage_desc: "유럽의 기독교 예술 유산을 통해 주님의 깊은 임재를 경험하세요.", footer_rights: "© 2026 영국 데일리 바이블. All rights reserved.",
        about_title: "사이트 소개: 오늘의 성경 구절 & 신앙 성장 플랫폼", vision_title: "우리의 비전", vision_desc: "이 사이트는 바쁜 현대 사회를 살아가는 모든 크리스천들이 매일의 삶 속에서 하나님의 말씀을 잊지 않고, 기도를 통해 주님과 동행하는 삶을 살 수 있도록 돕기 위해 설립되었습니다.", services_title: "제공하는 서비스", service_1: "오늘의 성경 구절: 매일 새로운 말씀과 기도 구절을 통해 영적 에너지를 공급받습니다.", service_2: "제자상 테스트: 성경적 기준을 바탕으로 현재 자신의 제자도를 다각도로 분석해 봅니다.", service_3: "신앙 점검: 자신의 영적 상태를 기록하고 추이를 확인하여 균형 잡힌 신앙 성장을 돕습니다.", service_4: "신앙 대시보드: 개인화된 데이터를 통해 자신의 영적 여정을 한눈에 파악할 수 있습니다.", meditation_title: "묵상을 위한 말씀", how_to_use_title: "사이트 활용 방법", how_to_use_desc: "1. 매일 아침 '오늘의 구절'로 하루를 시작하세요. 2. '신앙 점검'으로 주님과의 관계를 기록하세요. 3. '제자상 테스트'로 보완할 영역을 확인하세요.",
        blog_main_title: "AI 시대의 신앙생활 블로그", blog_subtitle: "급변하는 기술 시대 속에서 변하지 않는 진리를 탐구합니다.", btn_read_more: "더 보기",
        test_header: "AI 제자상 분석기", test_desc: "나의 얼굴상에 담긴 제자의 모습은 무엇일까요? 사진을 올려 확인해보세요.", test_alert: "* 사진은 서버에 저장되지 않고 브라우저에서만 분석됩니다.", upload_photo: "사진을 업로드해주세요", btn_select_photo: "사진 선택하기", analyzing: "AI가 당신의 제자상을 분석 중입니다...", btn_retry: "다른 사진으로 다시하기", model_error: "모델 URL이 설정되지 않았습니다.",
        checkup_title: "📋 주간 신앙 자가진단 (9문항)", checkup_subtitle: "각 질문에 솔직하게 답해 주세요.", label_name: "이름 (또는 닉네임)", placeholder_name: "이름을 입력하세요", section_1: "[영역 1] 내면의 평안과 우선순위", q1_title: "1. 이번 주 나의 마음 기상도는?", q1_option1: "맑음 (평안과 감사)", q1_option2: "흐림 (불안과 걱정)", q1_option3: "비/태풍 (영적 침체)", q2_title: "2. 일상 속 주님의 일하심을 느꼈나요?", q2_option1: "매우 그렇다", q2_option2: "보통이다", q2_option3: "잘 모르겠다", q3_title: "3. 이번 주 나의 우선순위 1번은?", q3_option1: "하나님", q3_option2: "가족/업무", q3_option3: "개인적 휴식/쾌락", section_2: "[영역 2] 말씀의 갈망과 순종", q4_title: "4. 설교 말씀 중 기억나는 단어가 있나요?", q4_option1: "명확히 기억남", q4_option2: "어렴풋함", q4_option3: "기억 안 남", q5_title: "5. 말씀을 삶에 적용하려고 노력했나요? (1~5점)", q6_title: "6. 실천을 방해하는 요소가 있었나요?", q6_option1: "매우 많았음", q6_option2: "조금 있었음", q6_option3: "거의 없었음", section_3: "[영역 3] 공동체와 사랑의 나눔", q7_title: "7. 공동체의 돌봄이 필요하다고 느끼나요?", q7_option1: "매우 필요/감사함", q7_option2: "가끔 느낌", q7_option3: "혼자가 편함", q8_title: "8. 다른 지체를 위해 기도나 섬김을 했나요?", q8_option1: "실천함", q8_option2: "마음만 먹음", q8_option3: "못 함", q9_title: "9. 교회가 나에게 생명을 공급하나요?", btn_submit: "결과 확인 및 데이터 저장", result_title: "📊 나의 신앙 밸런스 결과", spiritual_tip: "💡 영적 팁: 가장 점수가 낮은 영역을 이번 주 집중 기도 제목으로 삼아보세요.", btn_retest: "다시 테스트하기", save_success: "저장 성공! 결과가 저장되었습니다.", save_fail: "저장 실패: 데이터를 불러오지 못했습니다.",
        dashboard_title: "신앙 점검 대시보드", community_health: "📊 공동체 영적 건강도 (평균)", recent_records: "📋 최근 점검 기록", col_name: "이름", col_sensitivity: "영적 민감성", col_priority: "우선순위", col_receptivity: "말씀 수용성", col_obedience: "실천적 순종", col_community: "공동체 의식", col_sharing: "사랑의 나눔", col_date: "제출일", btn_checkup_now: "나도 점검하기",
        privacy_title: "개인정보처리방침", privacy_content: "본 사이트는 이용자의 개인정보를 중요시하며, 관련 법규를 준수합니다. 별도의 회원가입 없이 이용 가능하며, 서비스 개선 및 구글 애드센스 분석을 위해 쿠키를 통해 브라우저 설정 정보를 수집할 수 있습니다.", terms_title: "이용약관", terms_content: "영국 데일리 바이블에 오신 것을 환영합니다. 본 사이트는 성경 구절, 신앙 점검, AI 분석 등의 콘텐츠를 무료로 제공합니다. 모든 정보는 참고용입니다.", btn_go_home: "홈으로 돌아가기",
        arch_peter: "열정의 베드로", arch_peter_desc: "당신은 주님을 향한 뜨거운 열정을 가진 베드로와 닮았습니다.", arch_andrew: "묵묵한 안드레", arch_andrew_desc: "당신은 보이지 않는 곳에서 묵묵히 영혼들을 주님께로 인도하는 안드레와 닮았습니다.", arch_john: "사랑의 요한", arch_john_desc: "당신은 주님의 사랑을 깊이 깨닫고 그 사랑을 전하는 요한과 닮았습니다.", arch_paul: "이방인의 사도 바울", arch_paul_desc: "당신은 지적인 통찰과 폭발적인 전도 열정을 가진 바울과 닮았습니다.",
        faith_type_1: "민감한 동행자", faith_type_1_desc: "주님의 세밀한 음성에 귀 기울이는 모습이 아름답습니다.", faith_type_2: "충성된 일꾼", faith_type_2_desc: "하나님 나라를 위해 헌신하는 당신의 손길이 귀합니다.", faith_type_3: "말씀의 사람", faith_type_3_desc: "말씀을 사랑하는 당신, 깊은 묵상이 삶의 능력이 될 것입니다.", growth_area: "집중 보완 필요 영역", chart_label: "나의 신앙 밸런스"
    },
    en: {
        nav_home: "Home", nav_blog: "Blog", nav_about: "About", nav_test: "AI Disciple", nav_checkup: "Faith Check", nav_dashboard: "Dashboard", nav_privacy: "Privacy", nav_terms: "Terms", site_logo: "British Daily Bible",
        main_title: "Daily Bible Verse", loading: "Loading...", btn_new_verse: "New Verse", btn_share: "Share", pilgrim_title: "The Pilgrim's Way", pilgrim_desc: "A daily spiritual step for those walking the pilgrimage of life.", btn_start_test: "Start AI Test", checkup_promo_desc: "Let AI analyze your spiritual traits.", heritage_title: "Faith & Christian Art", heritage_desc: "Experience the presence of God through European Christian artistic heritage.", footer_rights: "© 2026 British Daily Bible. All rights reserved.",
        about_title: "About Us: Daily Bible & Spiritual Growth Platform", vision_title: "Our Vision", vision_desc: "This site was established to help modern Christians stay connected to God's Word.", services_title: "Services Offered", service_1: "Daily Bible Verse: Receive spiritual energy through daily scriptures.", service_2: "Disciple Test: Analyze your discipleship based on biblical standards.", service_3: "Faith Checkup: Record your spiritual state for balanced growth.", service_4: "Faith Dashboard: Understand your spiritual journey at a glance.", meditation_title: "Verses for Meditation", how_to_use_title: "How to Use", how_to_use_desc: "1. Start with 'Daily Verse'. 2. Record your relationship via 'Faith Checkup'. 3. Check areas for growth.",
        blog_main_title: "Faith in the AI Era Blog", blog_subtitle: "Exploring unchanging truths in a rapidly changing technological age.", btn_read_more: "Read More",
        test_header: "AI Disciple Analyzer", test_desc: "What biblical disciple do you resemble? Upload a photo.", test_alert: "* Photos are analyzed only in the browser.", upload_photo: "Please upload a photo", btn_select_photo: "Select Photo", analyzing: "AI is analyzing...", btn_retry: "Retry", model_error: "Model URL not set.",
        checkup_title: "📋 Weekly Faith Self-Check", checkup_subtitle: "Please answer honestly.", label_name: "Name", placeholder_name: "Enter your name", section_1: "[Area 1] Inner Peace and Priorities", q1_title: "1. How is your heart's weather?", q1_option1: "Sunny", q1_option2: "Cloudy", q1_option3: "Stormy", q2_title: "2. Did you feel the Lord working?", q2_option1: "Very much", q2_option2: "Somewhat", q2_option3: "Not really", q3_title: "3. What was your #1 priority?", q3_option1: "God", q3_option2: "Family", q3_option3: "Pleasure", section_2: "[Area 2] Word and Obedience", q4_title: "4. Remember sermon keywords?", q5_title: "5. Applied the Word?", q6_title: "6. Any obstacles?", section_3: "[Area 3] Community and Sharing", q7_title: "7. Need community care?", q8_title: "8. Prayed for others?", q9_title: "9. Church provides life?", btn_submit: "Save & Results", result_title: "📊 My Faith Balance", spiritual_tip: "💡 Tip: Focus on the lowest scoring area for prayer.", btn_retest: "Retest", save_success: "Saved!", save_fail: "Failed to load data.",
        dashboard_title: "Faith Dashboard", community_health: "📊 Community Spiritual Health", recent_records: "📋 Recent Records", col_name: "Name", col_sensitivity: "Sensitivity", col_priority: "Priority", col_receptivity: "Receptivity", col_obedience: "Obedience", col_community: "Community", col_sharing: "Sharing", col_date: "Date", btn_checkup_now: "Check Now",
        privacy_title: "Privacy Policy", privacy_content: "We value your privacy. This site doesn't require registration. We use cookies for service improvement and analytics.", terms_title: "Terms of Use", terms_content: "Welcome. We provide free faith-based content for reference only.", btn_go_home: "Go Home",
        arch_peter: "Passionate Peter", arch_peter_desc: "You resemble Peter, with a burning passion for the Lord.", arch_andrew: "Silent Andrew", arch_andrew_desc: "You resemble Andrew, silently leading souls.", arch_john: "Loving John", arch_john_desc: "You resemble John, sharing the Lord's love.", arch_paul: "Paul, Apostle", arch_paul_desc: "You have a great mission to spread the gospel.",
        faith_type_1: "Sensitive Companion", faith_type_1_desc: "Your attentiveness to God's voice is beautiful.", faith_type_2: "Faithful Worker", faith_type_2_desc: "Your dedication is precious.", faith_type_3: "Person of the Word", faith_type_3_desc: "Deep meditation will be your strength.", growth_area: "Area for Growth", chart_label: "My Faith Balance"
    },
    es: {
        nav_home: "Inicio", nav_blog: "Blog", nav_about: "Acerca", nav_test: "Discípulo AI", nav_checkup: "Chequeo Fe", nav_dashboard: "Panel", nav_privacy: "Privacidad", nav_terms: "Términos", site_logo: "Biblia Diaria Británica",
        main_title: "Versículo Diario", loading: "Cargando...", btn_new_verse: "Nuevo Versículo", btn_share: "Compartir", pilgrim_title: "El Camino del Peregrino", pilgrim_desc: "Un paso espiritual diario.", btn_start_test: "Iniciar Prueba", checkup_promo_desc: "Analiza tus rasgos espirituales.", heritage_title: "Fe y Arte", heritage_desc: "Presencia de Dios en el arte europeo.", footer_rights: "© 2026 British Daily Bible.",
        about_title: "Acerca de nosotros", vision_title: "Nuestra Visión", vision_desc: "Ayudar a los cristianos a mantenerse conectados.", services_title: "Servicios", service_1: "Versículo Diario", service_2: "Prueba de Discípulo", service_3: "Chequeo de Fe", service_4: "Panel de Fe", meditation_title: "Meditación", how_to_use_title: "Cómo usar", how_to_use_desc: "1. Versículo. 2. Chequeo. 3. Prueba.",
        blog_main_title: "Blog de Fe e IA", blog_subtitle: "Verdades inmutables.", btn_read_more: "Leer más",
        test_header: "Analizador IA", test_desc: "¿A qué discípulo te pareces?", test_alert: "* Análisis en el navegador.", upload_photo: "Sube una foto", btn_select_photo: "Seleccionar", analyzing: "Analizando...", btn_retry: "Reintentar",
        checkup_title: "📋 Autoevaluación", checkup_subtitle: "Responde honestamente.", label_name: "Nombre", placeholder_name: "Tu nombre", section_1: "Paz y Prioridades", q1_title: "1. ¿Clima de tu corazón?", q2_title: "2. ¿Sientes al Señor?", q3_title: "3. ¿Prioridad #1?", section_2: "Palabra", q4_title: "4. ¿Palabras clave?", q5_title: "5. ¿Aplicación?", q6_title: "6. ¿Obstáculos?", section_3: "Comunidad", q7_title: "7. ¿Cuidado?", q8_title: "8. ¿Oración?", q9_title: "9. ¿Vida?", btn_submit: "Ver Resultados", result_title: "📊 Balance de Fe", spiritual_tip: "💡 Consejo: Ora por tu área débil.", btn_retest: "Reintentar", save_success: "¡Guardado!", save_fail: "Error.",
        dashboard_title: "Panel de Fe", community_health: "📊 Salud Comunitaria", recent_records: "📋 Registros", col_name: "Nombre", col_sensitivity: "Sensibilidad", col_priority: "Prioridad", col_receptivity: "Receptividad", col_obedience: "Obediencia", col_community: "Comunidad", col_sharing: "Amor", col_date: "Fecha", btn_checkup_now: "Chequear Ahora",
        privacy_title: "Privacidad", privacy_content: "Valoramos tu privacidad. No requerimos registro.", terms_title: "Términos", terms_content: "Contenido gratuito para referencia.", btn_go_home: "Ir a Inicio",
        arch_peter: "Pedro", arch_andrew: "Andrés", arch_john: "Juan", arch_paul: "Pablo",
        faith_type_1: "Compañero", faith_type_2: "Trabajador", faith_type_3: "Palabra", growth_area: "Área de crecimiento", chart_label: "Mi Balance"
    },
    fr: {
        nav_home: "Accueil", nav_blog: "Blog", nav_about: "À propos", nav_test: "Disciple IA", nav_checkup: "Bilan Foi", nav_dashboard: "Tableau", nav_privacy: "Confidentialité", nav_terms: "Conditions", site_logo: "Bible Quotidienne Britannique",
        main_title: "Verset du Jour", loading: "Chargement...", btn_new_verse: "Nouveau Verset", btn_share: "Partager", pilgrim_title: "Le Chemin du Pèlerin", pilgrim_desc: "Un pas spirituel quotidien.", btn_start_test: "Démarrer Test", checkup_promo_desc: "Analyse spirituelle par IA.", heritage_title: "Foi et Art", heritage_desc: "Art chrétien européen.", footer_rights: "© 2026 British Daily Bible.",
        about_title: "À propos", vision_title: "Notre Vision", vision_desc: "Aider les chrétiens à rester connectés.", services_title: "Services", service_1: "Verset Quotidien", service_2: "Test Disciple", service_3: "Bilan Foi", service_4: "Tableau de Bord", meditation_title: "Méditation", how_to_use_title: "Utilisation", how_to_use_desc: "1. Verset. 2. Bilan. 3. Test.",
        blog_main_title: "Blog Foi et IA", blog_subtitle: "Vérités immuables.", btn_read_more: "Lire la suite",
        test_header: "Analyseur IA", test_desc: "Quel disciple êtes-vous ?", test_alert: "* Analyse locale.", upload_photo: "Télécharger une photo", btn_select_photo: "Choisir", analyzing: "Analyse...", btn_retry: "Réessayer",
        checkup_title: "📋 Auto-évaluation", checkup_subtitle: "Soyez honnête.", label_name: "Nom", placeholder_name: "Votre nom", section_1: "Paix et Priorités", q1_title: "1. Météo du cœur ?", q2_title: "2. Action de Dieu ?", q3_title: "3. Priorité #1 ?", section_2: "Parole", q4_title: "4. Mots clés ?", q5_title: "5. Application ?", q6_title: "6. Obstacles ?", section_3: "Communauté", q7_title: "7. Soins ?", q8_title: "8. Prière ?", q9_title: "9. Vie ?", btn_submit: "Résultats", result_title: "📊 Bilan de Foi", spiritual_tip: "💡 Conseil: Priez pour vos faiblesses.", btn_retest: "Réessayer", save_success: "Enregistré !", save_fail: "Erreur.",
        dashboard_title: "Tableau de Bord", community_health: "📊 Santé Communautaire", recent_records: "📋 Dossiers", col_name: "Nom", col_sensitivity: "Sensibilité", col_priority: "Priorité", col_receptivity: "Réceptivité", col_obedience: "Obéissance", col_community: "Communauté", col_sharing: "Amour", col_date: "Date", btn_checkup_now: "Vérifier",
        privacy_title: "Confidentialité", privacy_content: "Respect de la vie privée. Pas d'inscription.", terms_title: "Conditions", terms_content: "Contenu gratuit.", btn_go_home: "Accueil",
        arch_peter: "Pierre", arch_andrew: "André", arch_john: "Jean", arch_paul: "Paul",
        faith_type_1: "Compagnon", faith_type_2: "Ouvrier", faith_type_3: "Parole", growth_area: "Zone de croissance", chart_label: "Mon Bilan"
    }
};
